apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels: 
    project: expense
    app: frontend
    tier: web
spec:
  replicas: 2
  selector: 
    matchLabels:
      project: expense
      app: frontend
      tier: web
  template:
    metadata:
      labels:
        project: expense
        app: frontend
        tier: web
    spec:
      containers:
      - name: frontend
        image: mlndockerhub/frontend:v1

---
apiVersion: v1 
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector: 
    project: expense
    tier: web
    app: frontend
  ports:
  - name: frontend-svc-port
    protocol: "TCP"
    port: 80
    targetPort: 80

