# headless service has no clusterIP and it is used in statefulset
apiVersion: v1 
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None # for headless service there is no clusterIP
  selector:
    project: expense
    component: mysql 
    tier: db
  ports:
  - protocol: "TCP"
    port: 3306
    targetPort: 3306

---
apiVersion: v1 
kind: Service
metadata:
  name: mysql
  namespace: expense # normal service
spec:
  selector:
    project: expense
    component: mysql
    tier: db
  ports:
  - name: mysql-svc-port
    protocol: "TCP"
    port: 3306
    targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: mysql
  namespace: expense 
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      component: mysql
      tier: db
  serviceName: "mysql-headless" #statefulset headless service is referred
  # this is the headless service should be mentioned for statefulset
  template:
    metadata:
      labels:
        project: expense
        component: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: mlndockerhub/mysql:v1
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec: 
      accessModes: ["ReadWriteOnce"]
      storageClassName: "expense-ebs"
      resources:
        requests:
          storage: 5Gi